/*
 * JanelaPrincipal.java
 *
 * Created on __DATE__, __TIME__
 */

package visao.gui;

/**
 *
 * @author  __USER__
 */
@SuppressWarnings("serial")
public class JanelaPrincipal extends javax.swing.JFrame {

	/** Creates new form JanelaPrincipal */
	public JanelaPrincipal() {
		initComponents();

		new MediatorPrincipal(this);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">
	private void initComponents() {
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jSeparator1 = new javax.swing.JSeparator();
		jMenuItem2 = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Solucionador de d\u00favidas baseado no conhecimento do usu\u00e1rio");
		setResizable(false);
		jLabel1.setText("Pergunta");
		jPanel1.add(jLabel1);

		jPanel1.add(jComboBox1);

		getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

		jTextArea1.setColumns(20);
		jTextArea1.setLineWrap(true);
		jTextArea1.setRows(5);
		jTextArea1.setWrapStyleWord(true);
		jScrollPane1.setViewportView(jTextArea1);

		getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

		jMenu1.setText("Principal");
		jMenuItem1.setText("Sobre...");
		jMenu1.add(jMenuItem1);

		jMenu1.add(jSeparator1);

		jMenuItem2.setText("Sair");
		jMenu1.add(jMenuItem2);

		jMenuBar1.add(jMenu1);

		setJMenuBar(jMenuBar1);

		java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit()
				.getScreenSize();
		setBounds((screenSize.width - 489) / 2, (screenSize.height - 427) / 2,
				489, 427);
	}// </editor-fold>//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JTextArea jTextArea1;

	// End of variables declaration//GEN-END:variables
	public javax.swing.JComboBox getJComboBox1() {
		return jComboBox1;
	}

	public javax.swing.JMenuItem getJMenuItem1() {
		return jMenuItem1;
	}

	public javax.swing.JMenuItem getJMenuItem2() {
		return jMenuItem2;
	}

	public javax.swing.JTextArea getJTextArea1() {
		return jTextArea1;
	}

}